openapi: 3.0.0
info:
  description: API for the Ratings of laWiki web appplication. It provides all endpoints
    related to CRUD operatios for ratings.
  title: RatingsAPI
  version: "1.0"
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/DAVIDBUENOCARMONA_1/RatingsAPI/0.1
paths:
  /ratings/{id}:
    delete:
      description: Delete the rating associated with the selected ID
      operationId: delete-rating
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Deleted successfully
        "400":
          description: "Bad Request, invalid Rating ID format"
        "403":
          description: No permissions to delete
        "404":
          description: Rating Not Found
      summary: Delete Rating
      tags: []
    get:
      description: Get the Rating with the provided ID
      operationId: get-rating
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              examples:
                Example 1:
                  value:
                    id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                    article_id: e4aad634-3311-4e79-b165-3911549b3b29
                    Author:
                      id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                      name: string
                      image: http://example.com
                    value: 0
                    creation_date: 2019-08-24
              schema:
                $ref: '#/components/schemas/Rating'
          description: Rating found and returned
        "400":
          description: "Bad Request, invalid Rating ID format"
        "404":
          description: Rating Not Found
      summary: Get Rating
      tags: []
  /ratings/articles/{id}:
    delete:
      operationId: delete-ratings-articles-id
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
        "404":
          description: Not Found
      summary: Delete all ratings associated to an article
      tags: []
    post:
      description: Create a rating for a given Article
      operationId: rate-article
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewRating'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rating'
          description: Rating created
        "400":
          description: "Bad Request, invalid Article ID format"
        "403":
          description: Forbidden
        "404":
          description: Not Found
      summary: Rate Article
      tags: []
    put:
      description: Update the value of an already existing Rating
      operationId: edit-article-rating
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            examples:
              Example 1:
                value:
                  id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                  article_id: e4aad634-3311-4e79-b165-3911549b3b29
                  Author:
                    id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                    name: string
                    image: http://example.com
                  value: 0
                  creation_date: 2019-08-24
            schema:
              $ref: '#/components/schemas/Rating'
      responses:
        "201":
          content:
            application/json:
              examples:
                Example 1:
                  value:
                    id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                    article_id: e4aad634-3311-4e79-b165-3911549b3b29
                    Author:
                      id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                      name: string
                      image: http://example.com
                    value: 0
                    creation_date: 2019-08-24
              schema:
                $ref: '#/components/schemas/Rating'
          description: Rating edited
        "400":
          description: "Bad Request, invalid Article ID format"
        "403":
          description: Forbidden
        "404":
          description: Not Found
      summary: Edit Article's Rating
      tags: []
  /ratings/articles/{id}/average:
    get:
      description: Get data about the average rating of the article
      operationId: get-article-average-rating
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AverageRating'
          description: OK
        "400":
          description: "Bad Request, invalid Article ID format"
      summary: Get Article's average rating
      tags: []
  /ratings/articles/{articleId}/users/{userId}:
    get:
      operationId: get-ratings-bu-user-on-article
      parameters:
      - explode: false
        in: path
        name: articleId
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: userId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rating'
          description: OK
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity (WebDAV)
      summary: Get rating made by an user in an article
      tags: []
components:
  schemas:
    NewRating:
      description: "New Rating, created by one user associated with one article (Article\
        \ ID is obtained in path)"
      example:
        author_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        value: 0.8008281904610115
      properties:
        author_id:
          description: "Author ID: ID of the person who publish the rating"
          format: uuid
          title: author_id
          type: string
          x-stoplight:
            id: q4bc1zm0v0tt4
        value:
          description: "Value: The value of the rating published"
          title: value
          type: number
          x-stoplight:
            id: b3wl5oq26a7ik
      required:
      - author_id
      - value
      title: NewRating
      type: object
      x-examples:
        Example 1:
          author_id: 78424c75-5c41-4b25-9735-3c9f7d05c59e
          rating: 5
    Rating:
      description: Rating of an Article
      example:
        article_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        Author:
          image: https://openapi-generator.tech
          name: name
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        creation_date: 2000-01-23
        value: 0.8008281904610115
      properties:
        id:
          description: "Rating ID\r\n"
          format: uuid
          title: id
          type: string
        article_id:
          description: Article ID where the rating is published
          format: uuid
          title: article_id
          type: string
          x-stoplight:
            id: uzi095sjp0udm
        Author:
          $ref: '#/components/schemas/Author'
        value:
          description: Rating's value
          title: value
          type: number
          x-stoplight:
            id: 2n2knofgepww9
        creation_date:
          description: Date where the rating was published
          format: date
          title: creation_date
          type: string
          x-stoplight:
            id: s2jphmehddzvv
      required:
      - Author
      - article_id
      - creation_date
      - id
      - value
      title: Rating
      type: object
      x-examples:
        Example 1:
          id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
          article_id: e4aad634-3311-4e79-b165-3911549b3b29
          Author:
            id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
            name: string
            image: http://example.com
          value: 0
          creation_date: 2019-08-24
    Author:
      description: The author of a Rating
      example:
        image: https://openapi-generator.tech
        name: name
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        id:
          description: Author's ID on database
          format: uuid
          title: id
          type: string
        name:
          description: 'Author''s name '
          title: name
          type: string
          x-stoplight:
            id: qb0c3tnhxfrd2
        image:
          description: Author's profile image
          format: uri
          title: image
          type: string
          x-stoplight:
            id: nhj8lampltfr6
      required:
      - id
      - image
      - name
      title: Author
      type: object
      x-examples:
        Example 1:
          id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
          name: string
          image: http://example.com
    AverageRating:
      description: Data of the average rating of an Article
      example:
        one_count: 7
        average: 0.8008281904610115
        total: 6
        four_count: 5
        two_count: 2
        five_count: 1
        total_sum: 9
        three_count: 5
      properties:
        average:
          description: Average rating of an Article
          format: double
          title: average
          type: number
          x-stoplight:
            id: xc8d4rg2zmeoe
        total:
          description: Total number of Ratings of an Article
          title: total
          type: integer
          x-stoplight:
            id: 1hpzs5e0yz51f
        five_count:
          description: Number of 5-star ratings of an Article
          title: five_count
          type: integer
          x-stoplight:
            id: tgwuumk1xy9rq
        four_count:
          description: Number of 4-star ratings of an Article
          title: four_count
          type: integer
          x-stoplight:
            id: v5hqxo4zght6z
        three_count:
          description: Number of 3-star ratings of an Article
          title: three_count
          type: integer
          x-stoplight:
            id: q3vgda4tu3qrf
        two_count:
          description: Number of 2-star ratings of an Article
          title: two_count
          type: integer
          x-stoplight:
            id: yt0gl4isfgmc8
        one_count:
          description: Number of 1-star ratings of an Article
          title: one_count
          type: integer
          x-stoplight:
            id: 4rssmlpes2jtm
        total_sum:
          title: total_sum
          type: integer
          x-stoplight:
            id: yjg5812o4dc9c
      required:
      - average
      - five_count
      - four_count
      - one_count
      - three_count
      - total
      - total_sum
      - two_count
      title: AverageRatingData
      type: object
      x-examples:
        Example 1:
          average: 0
          total: 0
          five_count: 0
          four_count: 0
          three_count: 0
          two_count: 0
          one_count: 0
