openapi: 3.0.0
info:
  description: API for the tags microservice of laWiki web appplication. It provides
    all endpoints related to CRUD operatios for wiki tags.
  title: TagAPI
  version: "3.0"
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/ez3/tags-api/0.1
paths:
  /v2/tags/{id}:
    delete:
      description: Delete a wiki tag.
      operationId: delete-tag-v2
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: "No Content, tag deleted succesfully"
        "400":
          description: "Bad Request, invalid ID format"
        "403":
          description: Forbidden
        "404":
          description: Tag not found
      summary: Delete Tag
      tags:
      - v2/editors
    get:
      description: 'Get a tag by ID. '
      operationId: get-tag-v2
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagV2'
          description: OK
        "400":
          description: "Bad Request, invalid Tag ID format"
        "403":
          description: Forbidden
        "404":
          description: Tag not found
      summary: Get Tag
      tags:
      - v2/public
  /v2/tags/wikis/{id}:
    delete:
      description: Delete all tags from a wiki.
      operationId: delete-wiki-tags-v2
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: "No Content, tags deleted successfully"
        "400":
          description: "Bad Request, Incorrect ID format"
        "403":
          description: Forbidden
        "404":
          description: Wiki not found
      summary: Delete Wiki Tags
      tags:
      - v2/internal
    get:
      description: Retrieve all the tags from a wiki.
      operationId: get-wiki-tags-v2
      parameters:
      - description: The unique ID of the wiki.
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - description: Maximum amount of responses to be returned
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 20
          example: 20
          maximum: 100
          minimum: 0
          type: integer
        style: form
      - description: The index of the first result to return. Use with limit to get
          the next page of search results.
        explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 0
          example: 0
          minimum: 0
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagListV2'
          description: OK
        "400":
          description: "Bad Request, invalid parameters"
        "404":
          description: Wiki not found
      summary: Get Wikis Tags
      tags:
      - v2/public
    post:
      description: Create a new tag in a given wiki.
      operationId: post-wiki-tag-v2
      parameters:
      - description: The unique ID of the wiki.
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTagV2'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagV2'
          description: OK
        "400":
          description: "Bad Request, wrong content structure"
        "403":
          description: Forbidden
      summary: Create Tag
      tags:
      - v2/editors
  /v2/tags/articles/{id}:
    delete:
      description: "Unassigns a list of tags, given their IDs to an article."
      operationId: unassign-tags-v2
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - description: List of Tag IDs
        explode: false
        in: query
        name: ids
        required: true
        schema:
          example:
          - tag1
          - tag2
          items:
            type: string
          maxItems: 50
          type: array
          uniqueItems: true
        style: form
      responses:
        "204":
          description: "No Content, tag unassigned succesfully"
        "400":
          description: "Bad Request, invalid invalid paramaters format"
        "403":
          description: Forbidden
        "404":
          description: Article or tag not found
      summary: Unassign Tags
      tags:
      - v2/editors
    get:
      description: Retrieves all the tags from an article.
      operationId: get-articles-tags-v2
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - description: Maximum amount of responses to be returned
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 20
          example: 20
          maximum: 100
          minimum: 0
          type: integer
        style: form
      - description: The index of the first result to return. Use with limit to get
          the next page of search results.
        explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 0
          example: 0
          minimum: 0
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagListV2'
          description: OK
        "400":
          description: "Bad Request, invalid parameters"
        "404":
          description: Article not found
      summary: Get Articles Tag
      tags:
      - v2/public
    put:
      description: "Assigns a list of tags, given their IDs, to an article."
      operationId: assign-tags-v2
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            examples:
              Example 1:
                value:
                  tag_ids:
                  - 497f6eca-6276-4993-bfeb-53cbbbba6f08
            schema:
              $ref: '#/components/schemas/TagIDList'
      responses:
        "204":
          description: "No Content, tags assigned"
        "400":
          description: "Bad Request, invalid paramaters format"
        "403":
          description: Forbidden
        "404":
          description: Article or tag not found
      summary: Assign Tags
      tags:
      - v2/editors
  /v1/tags/{id}:
    delete:
      description: Delete a wiki tag.
      operationId: delete-tag-v1
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: "No Content, tag deleted succesfully"
        "400":
          description: "Bad Request, invalid ID format"
        "403":
          description: Forbidden
        "404":
          description: Tag not found
      summary: Delete Tag
      tags:
      - v1/editors
    get:
      description: 'Get a tag by ID. '
      operationId: get-tag-v1
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
          description: OK
        "400":
          description: "Bad Request, invalid Tag ID format"
        "403":
          description: Forbidden
        "404":
          description: Tag not found
      summary: Get Tag
      tags:
      - v1/public
  /v1/tags/wikis/{id}:
    get:
      description: Retrieve all the tags from a wiki.
      operationId: get-wiki-tags-v1
      parameters:
      - description: The unique ID of the wiki.
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - description: Maximum amount of responses to be returned
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 20
          example: 20
          maximum: 100
          minimum: 0
          type: integer
        style: form
      - description: The index of the first result to return. Use with limit to get
          the next page of search results.
        explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 0
          example: 0
          minimum: 0
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagList'
          description: OK
        "400":
          description: "Bad Request, invalid parameters"
        "404":
          description: Wiki not found
      summary: Get Wikis Tags
      tags:
      - v1/public
    post:
      description: Create a new tag in a given wiki.
      operationId: post-wiki-tag-v1
      parameters:
      - description: The unique ID of the wiki.
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTag'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
          description: OK
        "400":
          description: "Bad Request, wrong content structure"
        "403":
          description: Forbidden
      summary: Create Tag
      tags:
      - v1/editors
  /v1/tags/articles/{id}:
    delete:
      description: "Unassigns a list of tags, given their IDs to an article."
      operationId: unassign-tags-v1
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - description: List of Tag IDs
        explode: false
        in: query
        name: ids
        required: true
        schema:
          example:
          - tag1
          - tag2
          items:
            type: string
          maxItems: 50
          type: array
          uniqueItems: true
        style: form
      responses:
        "204":
          description: "No Content, tag unassigned succesfully"
        "400":
          description: "Bad Request, invalid invalid paramaters format"
        "403":
          description: Forbidden
        "404":
          description: Article or tag not found
      summary: Unassign Tags
      tags:
      - v1/editors
    get:
      description: Retrieves all the tags from an article.
      operationId: get-articles-tags-v1
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - description: Maximum amount of responses to be returned
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 20
          example: 20
          maximum: 100
          minimum: 0
          type: integer
        style: form
      - description: The index of the first result to return. Use with limit to get
          the next page of search results.
        explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 0
          example: 0
          minimum: 0
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagList'
          description: OK
        "404":
          description: Article not found
      summary: Get Articles Tag
      tags:
      - v1/public
    put:
      description: "Assigns a list of tags, given their IDs, to an article."
      operationId: assign-tags-v1
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            examples:
              Example 1:
                value:
                  tag_ids:
                  - 497f6eca-6276-4993-bfeb-53cbbbba6f08
            schema:
              $ref: '#/components/schemas/TagIDList'
      responses:
        "204":
          description: "No Content, tags assigned"
        "400":
          description: "Bad Request, invalid paramaters format"
        "403":
          description: Forbidden
        "404":
          description: Article or tag not found
      summary: Assign Tags
      tags:
      - v1/editors
  /v3/tags/{id}:
    delete:
      description: Delete a wiki tag.
      operationId: delete-tag-v3
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: user_id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - explode: false
        in: header
        name: admin
        required: true
        schema:
          type: boolean
        style: simple
      responses:
        "204":
          description: "No Content, tag deleted successfully"
        "400":
          description: "Bad Request, invalid ID format"
        "403":
          description: Forbidden
        "404":
          description: Tag not found
      summary: Delete Tag
      tags:
      - v3/editors
    get:
      description: Get a tag by ID.
      operationId: get-tag-v3
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagV2'
          description: OK
        "400":
          description: "Bad Request, invalid Tag ID format"
        "403":
          description: Forbidden
        "404":
          description: Tag not found
      summary: Get Tag
      tags:
      - v3/public
  /v3/tags/wikis/{id}:
    delete:
      description: Delete all tags from a wiki.
      operationId: delete-wiki-tags-v3
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: "No Content, tags deleted successfully"
        "400":
          description: "Bad Request, Incorrect ID format"
        "403":
          description: Forbidden
        "404":
          description: Wiki not found
      summary: Delete Wiki Tags
      tags:
      - v3/internal
    get:
      description: Retrieve all the tags from a wiki.
      operationId: get-wiki-tags-v3
      parameters:
      - description: The unique ID of the wiki.
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - description: Maximum amount of responses to be returned
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 20
          example: 20
          maximum: 100
          minimum: 0
          type: integer
        style: form
      - description: The index of the first result to return. Use with limit to get
          the next page of search results.
        explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 0
          example: 0
          minimum: 0
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagListV2'
          description: OK
        "400":
          description: "Bad Request, invalid parameters"
        "404":
          description: Wiki not found
      summary: Get Wikis Tags
      tags:
      - v3/public
    post:
      description: Create a new tag in a given wiki.
      operationId: post-wiki-tag-v3
      parameters:
      - description: The unique ID of the wiki.
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: user_id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - explode: false
        in: header
        name: admin
        required: true
        schema:
          type: boolean
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTagV2'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagV2'
          description: OK
        "400":
          description: "Bad Request, wrong content structure"
        "403":
          description: Forbidden
      summary: Create Tag
      tags:
      - v3/editors
  /v3/tags/articles/{id}:
    delete:
      description: "Unassigns a list of tags, given their IDs to an article."
      operationId: unassign-tags-v3
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - description: List of Tag IDs
        explode: false
        in: query
        name: ids
        required: true
        schema:
          example:
          - tag1
          - tag2
          items:
            type: string
          maxItems: 50
          type: array
          uniqueItems: true
        style: form
      - explode: false
        in: header
        name: user_id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - explode: false
        in: header
        name: admin
        required: false
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: "No Content, tags unassigned successfully"
        "400":
          description: "Bad Request, invalid parameters format"
        "403":
          description: Forbidden
        "404":
          description: Article or tag not found
      summary: Unassign Tags
      tags:
      - v3/editors
    get:
      description: Retrieves all the tags from an article.
      operationId: get-articles-tags-v3
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - description: Maximum amount of responses to be returned
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 20
          example: 20
          maximum: 100
          minimum: 0
          type: integer
        style: form
      - description: The index of the first result to return. Use with limit to get
          the next page of search results.
        explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 0
          example: 0
          minimum: 0
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagListV2'
          description: OK
        "400":
          description: "Bad Request, invalid parameters"
        "404":
          description: Article not found
      summary: Get Articles Tag
      tags:
      - v3/public
    put:
      description: "Assigns a list of tags, given their IDs, to an article."
      operationId: assign-tags-v3
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: user_id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - explode: false
        in: header
        name: admin
        required: true
        schema:
          type: boolean
        style: simple
      requestBody:
        content:
          application/json:
            examples:
              Example 1:
                value:
                  tag_ids:
                  - 497f6eca-6276-4993-bfeb-53cbbbba6f08
            schema:
              $ref: '#/components/schemas/TagIDList'
      responses:
        "204":
          description: "No Content, tags assigned"
        "400":
          description: "Bad Request, invalid parameters format"
        "403":
          description: Forbidden
        "404":
          description: Article or tag not found
      summary: Assign Tags
      tags:
      - v3/editors
components:
  schemas:
    TagV2:
      description: Tag entity.
      example:
        translations:
          key: translations
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        tag: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        wiki_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        articles:
        - name: name
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - name: name
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        id:
          description: The ID of the tag.
          format: uuid
          title: id
          type: string
        tag:
          description: The name of the tag.
          format: uuid
          title: tag
          type: string
          x-stoplight:
            id: g3ziz7fieuzmb
        wiki_id:
          description: The ID corresponding to the wiki the tag belongs to.
          format: uuid
          title: wiki_id
          type: string
          x-stoplight:
            id: ynzgbowu7wnwm
        articles:
          description: Array of articles that have the tag.
          items:
            $ref: '#/components/schemas/Article'
          title: articles
          type: array
          x-stoplight:
            id: 3qq291kyraib9
        translations:
          additionalProperties:
            type: string
            x-stoplight:
              id: cjfxqma13emzt
          description: A dictionary with tag translations to other languages.
          title: translations
          type: object
          x-stoplight:
            id: rqnw1ssgln7sp
      required:
      - articles
      - id
      - tag
      - translations
      - wiki_id
      title: TagV2
      type: object
      x-examples:
        Example 1:
          id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
          tag: string
          wiki_id: 9a3179cd-aa83-4a5b-a08a-5c794d4020a8
          articles:
          - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
            name: string
    Article:
      description: Article entity.
      example:
        name: name
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        id:
          description: The ID of the article.
          format: uuid
          title: id
          type: string
        name:
          description: The name of the article.
          title: name
          type: string
          x-stoplight:
            id: 7riv8a15yswa9
      required:
      - id
      - name
      title: Article
      type: object
      x-examples:
        Example 1:
          id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
          name: string
    NewTagV2:
      description: Model for a new Tag
      example:
        translation: true
        language: language
        tag: tag
      properties:
        tag:
          description: The name of the tag.
          title: tag
          type: string
          x-stoplight:
            id: yfh5p42q7b13x
        translation:
          description: It indicates if the translation is needed.
          title: translation
          type: boolean
          x-stoplight:
            id: o93iohhqtu5pf
        language:
          description: The original language of the tag.
          title: language
          type: string
          x-stoplight:
            id: hmq3ll11m1qoy
      required:
      - language
      - tag
      - translation
      title: NewTagV2
      type: object
      x-examples:
        Example 1:
          tag: string
    TagIDList:
      example:
        tag_ids:
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        tag_ids:
          description: List of Tag IDs
          items:
            format: uuid
            type: string
          title: tag_ids
          type: array
          x-stoplight:
            id: kmi9kpdl1ztoh
      required:
      - tag_ids
      title: TagIDsList
      type: object
      x-examples:
        Example 1:
          tag_ids:
          - 497f6eca-6276-4993-bfeb-53cbbbba6f08
    TagListV2:
      description: List of Tags. Supports pagination.
      example:
        next: https://openapi-generator.tech
        total: 0
        offset: 6
        previous: https://openapi-generator.tech
        limit: 0
        articles:
        - translations:
            key: translations
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          tag: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          wiki_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          articles:
          - name: name
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - name: name
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - translations:
            key: translations
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          tag: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          wiki_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          articles:
          - name: name
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - name: name
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        articles:
          items:
            $ref: '#/components/schemas/TagV2'
          title: articles
          type: array
          x-stoplight:
            id: qmckelb8p9agh
        total:
          description: The total number of items available to return.
          title: total
          type: integer
          x-stoplight:
            id: ceyp9h3u6pq3t
        offset:
          description: The offset of the items returned (as set in the query or by
            default)
          title: offset
          type: integer
          x-stoplight:
            id: y8f5uy4secbdp
        limit:
          description: The maximum number of items in the response (as set in the
            query or by default).
          example: 0
          minimum: 0
          title: limit
          type: integer
          x-stoplight:
            id: mli08w7p9m5ct
        previous:
          description: Request to the previous page of items. ( null if none)
          format: uri
          nullable: true
          title: previous
          type: string
          x-stoplight:
            id: fr352m14ihvc7
        next:
          description: 'Request to the next page of items. ( null if none) '
          format: uri
          nullable: true
          title: next
          type: string
          x-stoplight:
            id: d6rwzi2d4o45u
      required:
      - articles
      - limit
      - next
      - offset
      - previous
      - total
      title: TagListV2
      type: object
      x-examples:
        Example 1:
          articles:
          - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
            tag: string
            wiki_id: 9a3179cd-aa83-4a5b-a08a-5c794d4020a8
            articles:
            - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
              name: string
          total: 0
          offset: 0
          limit: 0
          previous: http://example.com
          next: http://example.com
    Tag:
      description: Tag entity.
      example:
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        tag: tag
        wiki_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        articles:
        - name: name
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - name: name
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        id:
          description: The ID of the tag.
          format: uuid
          title: id
          type: string
        tag:
          description: The name of the tag.
          title: tag
          type: string
          x-stoplight:
            id: g3ziz7fieuzmb
        wiki_id:
          description: The ID corresponding to the wiki the tag belongs to.
          format: uuid
          title: wiki_id
          type: string
          x-stoplight:
            id: ynzgbowu7wnwm
        articles:
          description: Array of articles that have the tag.
          items:
            $ref: '#/components/schemas/Article'
          title: articles
          type: array
          x-stoplight:
            id: 3qq291kyraib9
      required:
      - articles
      - id
      - tag
      - wiki_id
      title: Tag
      type: object
      x-examples:
        Example 1:
          id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
          tag: string
          wiki_id: 9a3179cd-aa83-4a5b-a08a-5c794d4020a8
          articles:
          - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
            name: string
    TagList:
      description: List of Tags. Supports pagination.
      example:
        next: https://openapi-generator.tech
        total: 0
        offset: 6
        previous: https://openapi-generator.tech
        limit: 0
        articles:
        - id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          tag: tag
          wiki_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          articles:
          - name: name
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - name: name
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          tag: tag
          wiki_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          articles:
          - name: name
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - name: name
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        articles:
          items:
            $ref: '#/components/schemas/Tag'
          title: articles
          type: array
          x-stoplight:
            id: qmckelb8p9agh
        total:
          description: The total number of items available to return.
          title: total
          type: integer
          x-stoplight:
            id: ceyp9h3u6pq3t
        offset:
          description: The offset of the items returned (as set in the query or by
            default)
          title: offset
          type: integer
          x-stoplight:
            id: y8f5uy4secbdp
        limit:
          description: The maximum number of items in the response (as set in the
            query or by default).
          example: 0
          minimum: 0
          title: limit
          type: integer
          x-stoplight:
            id: mli08w7p9m5ct
        previous:
          description: Request to the previous page of items. ( null if none)
          format: uri
          nullable: true
          title: previous
          type: string
          x-stoplight:
            id: fr352m14ihvc7
        next:
          description: 'Request to the next page of items. ( null if none) '
          format: uri
          nullable: true
          title: next
          type: string
          x-stoplight:
            id: d6rwzi2d4o45u
      required:
      - articles
      - limit
      - next
      - offset
      - previous
      - total
      title: TagList
      type: object
      x-examples:
        Example 1:
          articles:
          - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
            tag: string
            wiki_id: 9a3179cd-aa83-4a5b-a08a-5c794d4020a8
            articles:
            - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
              name: string
          total: 0
          offset: 0
          limit: 0
          previous: http://example.com
          next: http://example.com
    NewTag:
      description: Model for a new Tag
      example:
        tag: tag
      properties:
        tag:
          description: The name of the tag.
          title: tag
          type: string
          x-stoplight:
            id: yfh5p42q7b13x
      required:
      - tag
      title: NewTag
      type: object
      x-examples:
        Example 1:
          tag: string
