{
  "openapi": "3.0.0",
  "info": {
    "title": "Ratings",
    "description": "lawiki Ratings Api",
    "version": "0.1"
  },
  "servers": [
    {
      "url": "https://virtserver.swaggerhub.com/DAVIDBUENOCARMONA_1/RatingsAPI/0.1",
      "description": "SwaggerHub API Auto Mocking"
    }
  ],
  "paths": {
    "/ratings/{id}": {
      "get": {
        "tags": [],
        "summary": "Get rating by ID",
        "operationId": "get-ratings-id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Rating found and returned",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Rating"
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "article_id": "e4aad634-3311-4e79-b165-3911549b3b29",
                      "Author": {
                        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                        "name": "string",
                        "image": "http://example.com"
                      },
                      "value": 0,
                      "creation_date": "2019-08-24"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Rating Not Found"
          }
        }
      },
      "delete": {
        "tags": [],
        "summary": "Delete rating by ID",
        "description": "Delete the rating associated with the selected ID",
        "operationId": "delete-ratings-id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Deleted successfully"
          },
          "403": {
            "description": "No permissions to delete"
          },
          "404": {
            "description": "Rating Not Found"
          }
        }
      }
    },
    "/ratings/articles/{id}": {
      "get": {
        "tags": [],
        "summary": "Get all ratings of an article",
        "operationId": "get-ratings-article-id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "order",
            "in": "query",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "offset",
            "in": "query",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RatingList"
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "ratings": [
                        {
                          "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                          "article_id": "e4aad634-3311-4e79-b165-3911549b3b29",
                          "Author": {
                            "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                            "name": "string",
                            "image": "http://example.com"
                          },
                          "value": 0,
                          "creation_date": "2019-08-24"
                        }
                      ],
                      "limit": 0,
                      "offset": 0,
                      "total": 0,
                      "next": "http://example.com",
                      "previous": "http://example.com"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found"
          }
        }
      },
      "put": {
        "tags": [],
        "summary": "Edit rating of an article",
        "description": "This endpoint must do the same as Post but editting the value instead of creating a new one",
        "operationId": "put-ratings-article-id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Rating"
              },
              "examples": {
                "Example 1": {
                  "value": {
                    "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                    "article_id": "e4aad634-3311-4e79-b165-3911549b3b29",
                    "Author": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "name": "string",
                      "image": "http://example.com"
                    },
                    "value": 0,
                    "creation_date": "2019-08-24"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Edited rating",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Rating"
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                      "article_id": "e4aad634-3311-4e79-b165-3911549b3b29",
                      "Author": {
                        "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                        "name": "string",
                        "image": "http://example.com"
                      },
                      "value": 0,
                      "creation_date": "2019-08-24"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          }
        }
      },
      "post": {
        "tags": [],
        "summary": "Create rating on article",
        "operationId": "post-ratings-article-id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/NewRating"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Create a new rating related with an article, this MUST change the author's rating",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Rating"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/ratings/users/{id}": {
      "get": {
        "tags": [],
        "summary": "Get the rating from an user",
        "operationId": "get-ratings-user-id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Return the user rating",
            "content": {
              "application/json": {
                "schema": {
                  "type": "number"
                }
              }
            }
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/ratings/articles/{id}/average": {
      "get": {
        "tags": [],
        "summary": "Get average rating on selected Article",
        "operationId": "get-ratings-article-id-average",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_200"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "NewRating": {
        "title": "NewRating",
        "required": [
          "author_id",
          "value"
        ],
        "type": "object",
        "properties": {
          "author_id": {
            "type": "string",
            "description": "Author ID: ID of the person who publish the rating",
            "format": "uuid",
            "x-stoplight": {
              "id": "q4bc1zm0v0tt4"
            }
          },
          "value": {
            "type": "number",
            "description": "Value: The value of the rating published",
            "x-stoplight": {
              "id": "b3wl5oq26a7ik"
            }
          }
        },
        "description": "New Rating, created by one user associated with one article (Article ID is obtained in path)",
        "x-examples": {
          "Example 1": {
            "author_id": "78424c75-5c41-4b25-9735-3c9f7d05c59e",
            "rating": 5
          }
        }
      },
      "Rating": {
        "title": "Rating",
        "required": [
          "Author",
          "article_id",
          "creation_date",
          "id",
          "value"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "Rating ID\r\n",
            "format": "uuid"
          },
          "article_id": {
            "type": "string",
            "description": "Article ID where the rating is published",
            "format": "uuid",
            "x-stoplight": {
              "id": "uzi095sjp0udm"
            }
          },
          "Author": {
            "$ref": "#/components/schemas/Author"
          },
          "value": {
            "type": "number",
            "description": "Rating's value",
            "x-stoplight": {
              "id": "2n2knofgepww9"
            }
          },
          "creation_date": {
            "type": "string",
            "description": "Date where the rating was published",
            "format": "date",
            "x-stoplight": {
              "id": "s2jphmehddzvv"
            }
          }
        },
        "description": "Rating object, which content is obtained from the data base",
        "x-examples": {
          "Example 1": {
            "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
            "article_id": "e4aad634-3311-4e79-b165-3911549b3b29",
            "Author": {
              "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
              "name": "string",
              "image": "http://example.com"
            },
            "value": 0,
            "creation_date": "2019-08-24"
          }
        }
      },
      "Author": {
        "title": "Author",
        "required": [
          "id",
          "image",
          "name"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "Author's ID on database",
            "format": "uuid"
          },
          "name": {
            "type": "string",
            "description": "Author's name ",
            "x-stoplight": {
              "id": "qb0c3tnhxfrd2"
            }
          },
          "image": {
            "type": "string",
            "description": "Author's profile image",
            "format": "uri",
            "x-stoplight": {
              "id": "nhj8lampltfr6"
            }
          }
        },
        "x-examples": {
          "Example 1": {
            "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
            "name": "string",
            "image": "http://example.com"
          }
        }
      },
      "RatingList": {
        "title": "RatingList",
        "type": "object",
        "properties": {
          "ratings": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Rating"
            },
            "x-stoplight": {
              "id": "d5eh6v2k20xgj"
            }
          },
          "limit": {
            "type": "integer",
            "x-stoplight": {
              "id": "3zrcx11uhb527"
            }
          },
          "offset": {
            "type": "integer",
            "x-stoplight": {
              "id": "qdopqbxi79y5p"
            }
          },
          "total": {
            "type": "integer",
            "x-stoplight": {
              "id": "72gdqe1ngz9hq"
            }
          },
          "next": {
            "type": "string",
            "format": "uri",
            "x-stoplight": {
              "id": "no5svtesm8hk2"
            }
          },
          "previous": {
            "type": "string",
            "format": "uri",
            "x-stoplight": {
              "id": "lu2ppdfowvavf"
            }
          }
        },
        "x-examples": {
          "Example 1": {
            "ratings": [
              {
                "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                "article_id": "e4aad634-3311-4e79-b165-3911549b3b29",
                "Author": {
                  "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
                  "name": "string",
                  "image": "http://example.com"
                },
                "value": 0,
                "creation_date": "2019-08-24"
              }
            ],
            "limit": 0,
            "offset": 0,
            "total": 0,
            "next": "http://example.com",
            "previous": "http://example.com"
          }
        }
      },
      "AverageRating": {
        "title": "AverageRating",
        "type": "object",
        "properties": {
          "average": {
            "type": "number",
            "x-stoplight": {
              "id": "xc8d4rg2zmeoe"
            }
          },
          "five_count": {
            "type": "integer",
            "x-stoplight": {
              "id": "tgwuumk1xy9rq"
            }
          },
          "four_count": {
            "type": "integer",
            "x-stoplight": {
              "id": "v5hqxo4zght6z"
            }
          },
          "three_count": {
            "type": "integer",
            "x-stoplight": {
              "id": "q3vgda4tu3qrf"
            }
          },
          "two_count": {
            "type": "integer",
            "x-stoplight": {
              "id": "yt0gl4isfgmc8"
            }
          },
          "one_count": {
            "type": "integer",
            "x-stoplight": {
              "id": "4rssmlpes2jtm"
            }
          }
        }
      },
      "inline_response_200": {
        "type": "object",
        "properties": {
          "average": {
            "type": "number",
            "x-stoplight": {
              "id": "0lnb4hf0vj6c9"
            }
          },
          "five_count": {
            "type": "integer",
            "x-stoplight": {
              "id": "xcnox0bx4b03p"
            }
          },
          "four_count": {
            "type": "integer",
            "x-stoplight": {
              "id": "psuaku1zueqhs"
            }
          },
          "three_count": {
            "type": "integer",
            "x-stoplight": {
              "id": "lcgwh2iq6eq7s"
            }
          },
          "two_count": {
            "type": "integer",
            "x-stoplight": {
              "id": "zucmrlvui19x1"
            }
          },
          "one_count": {
            "type": "integer",
            "x-stoplight": {
              "id": "q8s6fm622clq8"
            }
          },
          "total": {
            "type": "integer",
            "x-stoplight": {
              "id": "hlnqh9g8o1tnx"
            }
          }
        }
      }
    }
  }
}